dist: trusty
sudo: false

language: scala
jdk: oraclejdk8

scala:
  - 2.13.3
  - 2.12.12

script:
  -  sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
  -  sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

after_success:
  - pip install --user codecov && codecov
